# Generated by Django 5.1.7 on 2025-03-29 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_alter_officer_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_full_name', models.CharField(max_length=255)),
                ('request_dob', models.DateField()),
                ('request_address', models.TextField()),
                ('request_gender', models.CharField(max_length=10)),
                ('request_phone_number', models.CharField(max_length=20, unique=True)),
                ('request_email', models.EmailField(max_length=254, unique=True)),
                ('id_proof_name', models.CharField(max_length=20)),
                ('address_proof_name', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('id_proof_file', models.FileField(upload_to='id_proofs/')),
                ('address_proof_file', models.FileField(upload_to='address_proofs/')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
