# Generated by Django 5.1.7 on 2025-03-31 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_rejectedrequest'),
        ('user', '0003_alter_kycrequest_request_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedrequest',
            name='request_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.kycrequest'),
        ),
    ]
