# Generated by Django 5.1.7 on 2025-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0004_rejectedrequest_request_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectedrequest',
            name='request_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='rejectedrequest',
            name='request_phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
