# Generated by Django 5.1.7 on 2025-04-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("officer", "0005_alter_rejectedrequest_request_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Officer",
        ),
    ]
