# Generated by Django 5.1.7 on 2025-03-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0004_remove_citizen_address_proof_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proof_name', models.CharField(choices=[('Aadhaar', 'Aadhaar'), ('PAN', 'PAN Card'), ('DL', 'Driving License'), ('Passport', 'Passport'), ('Voter ID', 'Voter ID')], max_length=20)),
                ('address_proof_name', models.CharField(choices=[('Aadhaar', 'Aadhaar'), ('Passport', 'Passport'), ('Voter ID', 'Voter ID'), ('Electricity Bill', 'Electricity Bill'), ('Water Bill', 'Water Bill'), ('Bank Statement', 'Bank Statement'), ('Rent Agreement', 'Rent Agreement')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('id_proof_file', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('address_proof_file', models.FileField(blank=True, null=True, upload_to='address_proofs/')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_requests', to='Accounts.citizen')),
            ],
        ),
    ]
