# Generated by Django 5.1.7 on 2025-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_kycrequest_request_address_kycrequest_request_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrequest',
            name='request_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='request_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
