# Generated by Django 5.1.7 on 2025-04-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_kycrequest_request_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycrequest",
            name="request_id",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
