# Generated by Django 5.1.7 on 2025-04-07 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_proof_name",
                    models.CharField(
                        choices=[
                            ("Aadhaar", "Aadhaar"),
                            ("PAN", "PAN Card"),
                            ("DL", "Driving License"),
                            ("Passport", "Passport"),
                            ("Voter ID", "Voter ID"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "address_proof_name",
                    models.CharField(
                        choices=[
                            ("Aadhaar", "Aadhaar"),
                            ("Passport", "Passport"),
                            ("Voter ID", "Voter ID"),
                            ("Electricity Bill", "Electricity Bill"),
                            ("Water Bill", "Water Bill"),
                            ("Bank Statement", "Bank Statement"),
                            ("Rent Agreement", "Rent Agreement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "id_proof_file",
                    models.FileField(blank=True, null=True, upload_to="id_proofs/"),
                ),
                (
                    "address_proof_file",
                    models.FileField(
                        blank=True, null=True, upload_to="address_proofs/"
                    ),
                ),
                ("request_full_name", models.CharField(max_length=255, null=True)),
                ("request_dob", models.DateField(blank=True, null=True)),
                ("request_address", models.TextField(null=True)),
                ("request_gender", models.CharField(max_length=10, null=True)),
                (
                    "request_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("request_email", models.EmailField(max_length=254, null=True)),
                ("request_id", models.CharField(max_length=20, null=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_requests",
                        to="user.citizen",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RejectedRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_full_name", models.CharField(max_length=255)),
                ("request_dob", models.DateField()),
                ("request_address", models.TextField()),
                ("request_gender", models.CharField(max_length=10)),
                ("request_phone_number", models.CharField(max_length=20)),
                ("request_email", models.EmailField(max_length=254)),
                ("id_proof_name", models.CharField(max_length=20)),
                ("address_proof_name", models.CharField(max_length=20)),
                ("submitted_at", models.DateTimeField()),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("id_proof_file", models.FileField(upload_to="id_proofs/")),
                ("address_proof_file", models.FileField(upload_to="address_proofs/")),
                (
                    "request_obj",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kyc_approval_app.kycrequest",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
