# Generated by Django 5.1.7 on 2025-03-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
