# Generated by Django 5.1.7 on 2025-03-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_citizen_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='address_proof_file',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='id_proof_file',
        ),
    ]
